version: '3.8'

networks:
    be-i-prod:

services:
    nginx_backend_prod:
        image: nginx:stable
        container_name: ${APP_NAME}_nginx
        restart: unless-stopped
        ports:
            - "8081:80"
        links:
            - php_backend_prod
        volumes:
            - ~/Program/backend/docker/nginx/site-prod.conf:/etc/nginx/conf.d/default.conf:rw
            - ~/Program/backend/docker/logs/nginx:/var/logs/nginx:rw
        depends_on:
            - php_backend_prod
            - postgres_backend_prod
        networks:
            - be-i-prod
    php_backend_prod:
        image: ${APP_IMAGE_PROD}:${APP_IMAGE_PROD_TAG}
        container_name: ${APP_NAME}_php
        restart: unless-stopped
        volumes:
            - ~/Program/backend/storage:/var/www/html/storage:rw
        env_file: .env
        environment:
            DB_HOST: postgres_backend_prod
        depends_on:
            - postgres_backend_prod
        networks:
            - be-i-prod
    postgres_backend_prod:
        image: postgres:14.2-alpine
        container_name: ${APP_NAME}_postgres
        restart: unless-stopped
        ports:
            - "5436:5432"
        volumes:
            - ~/Program/backend/docker/postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_HOST_AUTH_METHOD: "trust"
        networks:
            - be-i-prod
